name: Run Summarization Bot

on:
  schedule:
    - cron: "*/1 * * * *"
  workflow_dispatch:  # Manual trigger option from GitHub UI

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9  #

      - name: Install dependencies
        run: pip install -r requirements.txt 

      - name: Set environment variables
        run: |
          echo "APP_ID=${{ secrets.APP_ID }}" >> $GITHUB_ENV
          echo "APP_SECRET=${{ secrets.APP_SECRET }}" >> $GITHUB_ENV
          echo "USER_AGENT=${{ secrets.USER_AGENT }}" >> $GITHUB_ENV
          echo "REDDIT_USERNAME=${{ secrets.REDDIT_USERNAME }}" >> $GITHUB_ENV
          echo "REDDIT_PASSWORD=${{ secrets.REDDIT_PASSWORD }}" >> $GITHUB_ENV

          
      - name: Download NLTK resources
        run: python -m nltk.downloader punkt

      - name: Run script
        run: python src/sum_bot.py


      - name: Commit and push changes
        env:
          ACTIONS_BOT_TOKEN: ${{ secrets.ACTIONS_BOT_TOKEN }}
        run: |
          git config --local user.name "GitHub Action"
          git config --local user.email "action@github.com"
          git add .
          git commit -m "Update logs" --allow-empty
          git push https://github.com/${{ github.repository }}.git HEAD:${{ github.ref }} -f