name: Run Summarization Bot

on:
  schedule:
    - cron: "0 */2 * * *" #Run every 2 hours

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9  #

      - name: Install dependencies
        run: pip install -r requirements.txt 

      - name: Set environment variables
        run: |
          echo "APP_ID=${{ secrets.APP_ID }}" >> $GITHUB_ENV
          echo "APP_SECRET=${{ secrets.APP_SECRET }}" >> $GITHUB_ENV
          echo "USER_AGENT=${{ secrets.USER_AGENT }}" >> $GITHUB_ENV
          echo "REDDIT_USERNAME=${{ secrets.REDDIT_USERNAME }}" >> $GITHUB_ENV
          echo "REDDIT_PASSWORD=${{ secrets.REDDIT_PASSWORD }}" >> $GITHUB_ENV

          
      - name: Download NLTK resources
        run: python -m nltk.downloader punkt

      - name: Run script
        run: python src/sum_bot.py

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "updated logs" --allow-empty)
          
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.ACTIONS_SUM_BOT_TOKEN }}
          branch: main 